apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
  - port: 5555
    targetPort: 5555
    nodePort: 30080  # exposes at http://<minikube-ip>:30080
